# Generated by Django 6.0.3 on 2026-03-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.TextField(blank=True, verbose_name='프로젝트 설명'),
        ),
    ]
